// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efprmnbolknjrruuorgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmcHJtbmJvbGtuanJydXVvcmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTMwODksImV4cCI6MjA2NTcyOTA4OX0.9SE3xf68HhmEoruG2MFhp8gEJH7NdnUSVoHfwPOYcTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);